package(default_visibility = ["//:src"])

java_library(
    name = "inject",
    srcs = glob(["*.java"]),
    deps = [
        "@google_bazel_common//third_party/java/jsr305_annotations",
        "@google_bazel_common//third_party/java/jsr330_inject",
    ],
)
